//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp8
{
    using System;
    using System.Collections.Generic;
    
    public partial class AGENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AGENT()
        {
            this.EMAIL = new HashSet<EMAIL>();
            this.HISTORY = new HashSet<HISTORY>();
            this.OFFERS = new HashSet<OFFERS>();
            this.PHONE = new HashSet<PHONE>();
        }
    
        public int ID { get; set; }
        public string NAME_COMPANY { get; set; }
        public int ID_TYPE { get; set; }
        public string ADDRESS { get; set; }
        public int INN { get; set; }
        public int KPP { get; set; }
        public string DIRECTOR { get; set; }
        public byte[] LOGO { get; set; }
        public int ID_SELL_PLACE { get; set; }
        public string PRIORITY { get; set; }
    
        public virtual SELL_PLACE SELL_PLACE { get; set; }
        public virtual TYPE_AGENT TYPE_AGENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMAIL> EMAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HISTORY> HISTORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OFFERS> OFFERS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHONE> PHONE { get; set; }
    }
}
