//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp8
{
    using System;
    using System.Collections.Generic;
    
    public partial class MASTER_INDUSTRY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MASTER_INDUSTRY()
        {
            this.INDUSTRY = new HashSet<INDUSTRY>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
        public int ID_SCHEDULE { get; set; }
        public string FAMILY { get; set; }
        public string PROBLEM { get; set; }
    
        public virtual SCHEDULE SCHEDULE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INDUSTRY> INDUSTRY { get; set; }
    }
}
