//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp8
{
    using System;
    using System.Collections.Generic;
    
    public partial class MATERIAL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MATERIAL()
        {
            this.HISTORY_SUPPLIER = new HashSet<HISTORY_SUPPLIER>();
            this.SHIPMENT = new HashSet<SHIPMENT>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
        public Nullable<int> ID_TYPE_MATERIAL { get; set; }
        public Nullable<int> ID_SUPPLIER { get; set; }
        public Nullable<int> QUANTITY_PACKAGING { get; set; }
        public Nullable<int> ID_UNIT_OF_MEASUREMENT { get; set; }
        public Nullable<int> QUANTITY_STOREHOSE { get; set; }
        public Nullable<int> MIN_QUANTITY { get; set; }
        public string DESCRIPTION { get; set; }
        public byte[] IMAGE { get; set; }
        public Nullable<int> PRICE { get; set; }
        public string OPERATION { get; set; }
        public Nullable<int> ID_PRODUCT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HISTORY_SUPPLIER> HISTORY_SUPPLIER { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
        public virtual SUPPLIER SUPPLIER { get; set; }
        public virtual TYPE_MATERIAL TYPE_MATERIAL { get; set; }
        public virtual UNIT_OF_MEASUREMENT UNIT_OF_MEASUREMENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SHIPMENT> SHIPMENT { get; set; }
    }
}
