//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp8
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCT()
        {
            this.MATERIAL = new HashSet<MATERIAL>();
            this.OFFERS = new HashSet<OFFERS>();
        }
    
        public int ARTICLE { get; set; }
        public string NAME { get; set; }
        public int ID_TYPE_PRODUCT { get; set; }
        public string DESCRIPTION { get; set; }
        public byte[] IMAGE { get; set; }
        public decimal MIN_PRICE { get; set; }
        public string SIZE { get; set; }
        public int WEIGHT_ORIGINAL { get; set; }
        public int WEIGHT { get; set; }
        public byte[] QUALITY_CERTIFICATE { get; set; }
        public int ID_STANDART { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MATERIAL> MATERIAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OFFERS> OFFERS { get; set; }
        public virtual STANDART STANDART { get; set; }
        public virtual TYPE_PRODUCT TYPE_PRODUCT { get; set; }
    }
}
