//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp8
{
    using System;
    using System.Collections.Generic;
    
    public partial class SHIPMENT
    {
        public int ID { get; set; }
        public int ID_STOCKMAN { get; set; }
        public int ID_SUPPLIER { get; set; }
        public int ID_MATERIAL { get; set; }
    
        public virtual MATERIAL MATERIAL { get; set; }
        public virtual STOCKMAN STOCKMAN { get; set; }
        public virtual SUPPLIER SUPPLIER { get; set; }
    }
}
