//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp8
{
    using System;
    using System.Collections.Generic;
    
    public partial class TURNSTILE
    {
        public int ID { get; set; }
        public string NAME { get; set; }
        public int ID_INDUSTRY { get; set; }
    
        public virtual INDUSTRY INDUSTRY { get; set; }
    }
}
